name: Deployment
on:
  push:
    branches:
      - main
      - dev
env:
  MONGODB_DB_NAME: gha-demo # Workflow level env variable (works for all jobs in the WF)
jobs:
  test:
    env: # Job level env variable (works for only curren job in the WF)
      MONGODB_CLUSTER_ADDRESS: study-gh-actions.htlq5dn.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }} # Secrets defined on Github. settings/secrets
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8070
    environment: testing # Define an environment with separate configs (vars, secrets, filters) on github under settings/secrets
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # Syntax for using an env Variable
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
